# Generated by Django 3.2.7 on 2022-02-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220207_1554'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderClassItem',
            new_name='OrderLineItem',
        ),
    ]
